### ISSUE TITLE
Issue with rendering Persian words

### ISSUE THREAD

**Issue by ahbanavi** [behrouzbakhtiari/twitter-word-cloud#12]
Issue with rendering Persian words on Arch Linux.

![iyedoost](https://user-images.githubusercontent.com/39927312/75632665-a2948d80-5c13-11ea-89d1-03eac81771a1.png)

[output.zip](https://github.com/behrouzbakhtiari/twitter-word-cloud/files/4272334/output.zip)

Terminal output:
[log.txt](https://github.com/behrouzbakhtiari/twitter-word-cloud/files/4272347/log.txt)

**Comment by HrBDev** [comment]
arabic_shaper & python_bidi  are not needed anymore, you can fix this by getting rid of them.
You need to delete line 141 of twc.py: `text = get_display(arabic_reshaper.reshape(text))`.
