### ISSUE TITLE
مشکل انتخاب نام کاربری

### ISSUE THREAD

**Issue by thatmehdi** [behrouzbakhtiari/twitter-word-cloud#15]
در انتخاب یوزر توسط sys.argv داره آرگومان اول رو انتخاب میکنه که چون داره کلید -u میگیره یوزرنیم رو -u میگیره و ادامه میده کار رو نه نام کاربری و احتمالا همین مساله برای تعداد کلمات هم باشه که یه کلید اومده قبلش
باید شماره جایگاه ارگومان ها رو تغییر بدید

python twc.py -u twitter_username -c 100

**Comment by behrouzbakhtiari** [comment]
شما مطمن هستید که از آخرین آپدیت کد استفاده می‌کنید؟ چون توی نسخه آخر از 
sys.argv
استفاده نشده است. میتونید دقیق دستوری را که اجرا کرده بودید بنویسید که با همان من چک کنم؟

**Comment by thatmehdi** [comment]
احتمالش هست که نسخه من قدیمی باشه با توجه به اینکه الان دیدم پروژه اخیرا کامیت زیاد داشته. من کد رو هفته پیش دانلود کردم و چون
 c++ build tool 
رو سیستم نداشتم اجراش موکول شد به دیروز. کدی که من دارم دستورات
sys.argv
تو تابع 
main 
استفاده شده. من برای اجرا دستور 
python twc.py -u twitter_username
رو استفاده کردم که احتمالا باید به این صورت
python twc.py  username
استفاده میشد برای نسخه ای که دست من هست.

ممنون از توجه شما
