### ISSUE TITLE
استخراج ابر کلمات دو کلمه ای 

### ISSUE THREAD

**Issue by miladfa7** [behrouzbakhtiari/twitter-word-cloud#16]
چطور می تونم ابر کلمات دو کلمه ای رو با استفاده از برنامه پیدا کنم؟  آیا امکان پذیر است؟ 
برای پیدا کردن ابرکلمات در اسکیل بزرگتر راه حلی دارید؟

**Comment by behrouzbakhtiari** [comment]
منظورتان دقیقن از ابرکلمات دو کلمه‌ای چیست؟ با متن یک توییت می‌تونید مثال بزنید منظورتان را؟

**Comment by miladfa7** [comment]
یه همچین چیزی می خواستم که با بایگرم بدست آوردم 
nltk.bigram()

![Rouhani_ir2](https://user-images.githubusercontent.com/25765644/76159441-bbca9c00-6135-11ea-82bc-77f936ecd954.png)

**Comment by behrouzbakhtiari** [comment]
آره کاملن درسته با مدلی زبانی بایگرام اکی میشه این مورد. توی برنامه‌‌ام هست که اضافه کنم روی کد هم این مورد هم document frequency را

**Comment by behrouzbakhtiari** [comment]
اضافه کردم این مورد را هم
