### ISSUE TITLE
هنگ و لوپ در بعضی اکانتها، بعد از دانلود توییت ها

### ISSUE THREAD

**Issue by Shaheding** [behrouzbakhtiari/twitter-word-cloud#6]
سلام
تیتر واضحه. برای نمونه اکانت shaheding رو تست کنین.
مرسی.

**Comment by ahangarha** [comment]
<p dir=auto>وجود چنین مشکلی رو تایید می‌کنم. دریافت توییت‌ها در توییتی که پایین مشخص کرده‌ام متوقف می‌ماند.  اما پردازش توییت‌ها  هم در جایی گیر می‌کند که نیازمند بررسی و اشکال‌یابی است.</p>

I admit

I downloaded your tweets till `972400104392052736 2018-03-10 13:43:45 `. It didn't download more and got stuck.

I tried to used the existing csv file of retrieved tweets but it didn't proceed.

We need to debug and see what the problem is

**Comment by ahangarha** [comment]
<p dir=auto>مشکل، در پردازش توییتی است که چنین محتوایی دارد. بررسی بیشتر نشان می‌دهد مشکل در تابع clean_tweet بروز می‌کند. با حذف پیوند، برنامه ادامه یافته و ابر زیر را تولید می‌کند</p>

It cannot proccess this tweet:

> بیا اینو بخون 😕
 https://fa.wikipedia.org/wiki/%D8%AD%D9%85%D9%84%D9%87_%D8%A8%D9%87_%DA%A9%D9%88%DB%8C_%D8%AF%D8%A7%D9%86%D8%B4%DA%AF%D8%A7%D9%87_%D8%AA%D9%87%D8%B1%D8%A7%D9%86_(%DB%B1%DB%B8%E2%80%93%DB%B2%DB%B3_%D8%AA%DB%8C%D8%B1_%DB%B1%DB%B3%DB%B7%DB%B8) … 

It seems `clean_tweet` function cannot handle this link

After removing the link (manually from csv) the cloud was made:
![shaheding](https://user-images.githubusercontent.com/11241315/75623068-3f2f3f00-5bc4-11ea-91af-c21a9d755a0e.png)

**Comment by ahangarha** [comment]
<p dir=auto>بررسی بیشتر نشان می‌دهد که مشکل از بسته preprocessor ناشی می‌شود. این مشکل به توسعه دهندگان آن گزارش شد</p>

Clearly `preprocessor` cannot handle cleaning this link. I have reported it here: https://github.com/s/preprocessor/issues/29

**Comment by ahangarha** [comment]
@behrouzbakhtiari should we wait for them to patch this issue or we should add another layer of cleaning for removing links?

**Comment by behrouzbakhtiari** [comment]
@ahangarha I'll remove preprocessor and add new methods for removing links, mentions and...

**Comment by ahangarha** [comment]
> @ahangarha I'll remove preprocessor and add new methods for removing links, mentions and...

This would solve another issue regarding hashtags.

**Comment by behrouzbakhtiari** [comment]
I removed preprocessor package and updated clean method

**Comment by behrouzbakhtiari** [comment]
> سلام
> تیتر واضحه. برای نمونه اکانت shaheding رو تست کنین.
> مرسی.

میتونید یکبار دیگر با سورس جدید روی اکانت خودتان چک کنید و تایید کنید

**Comment by Shaheding** [comment]
> > سلام
> > تیتر واضحه. برای نمونه اکانت shaheding رو تست کنین.
> > مرسی.
> 
> میتونید یکبار دیگر با سورس جدید روی اکانت خودتان چک کنید و تایید کنید

تایید میکنم. مرتبه همه چیز. ممنون.
